import { TestCommandGenerator } from './TestCommandGenerator';
import { CmdRunner } from '../../modules/cli/CmdRunner';
import { TestScriptExecutionOptions } from '../../modules/ts/TestScriptExecution';
import { OutputFileWriter } from "../../modules/cli/OutputFileWriter";

/**
 * Executes test scripts generated by Concordia using CodeceptJS.
 * 
 * @author Matheus Eller Fagundes
 */
export class TestScriptExecutor {
    
    constructor( private _fileWriter: OutputFileWriter, private _cmd: CmdRunner, private _cmdGenerator: TestCommandGenerator ) {
    }

    /**
     * Executes the script according to the options given.
     * 
     * @param options Execution options
     */
    public execute( options: TestScriptExecutionOptions ): Promise< any > {
        // It's only possible to run CodeceptJS if there is a 'codecept.json' file in the folder.
        this._fileWriter.write( '{}', options.sourceCodeDir, 'codecept', 'json' );
        let testCommand: string = this._cmdGenerator.generateTestCommand( options );
        return this._cmd.run( testCommand );
    }

}
