import { TestScriptExecutionOptions } from '../../modules/testscript/TestScriptExecution';
import { CodeceptJSOptionsBuilder } from './CodeceptJSOptionsBuilder';
import * as path  from "path";
import * as fse from 'node-fs-extra';
import * as childProcess from 'child_process';
import { promisify } from 'util';
import { writeFile } from 'fs';

/**
 * Executes test scripts generated by Concordia using CodeceptJS.
 *
 * @author Matheus Eller Fagundes
 * @author Thiago Delgado Pinto
 */
export class TestScriptExecutor {

    /**
     * Executes the script according to the options given.
     *
     * @param options Execution options
     */
    public async execute( options: TestScriptExecutionOptions ): Promise< string > {

        if ( !! options.sourceCodeDir ) {
            fse.mkdirs( options.sourceCodeDir );
        }
        // It's only possible to run CodeceptJS if there is a 'codecept.json' file in the folder.
        const filePath: string = path.join( options.sourceCodeDir || '.', 'codecept.json' );
        const writeF = promisify( writeFile );
        await writeF( filePath, JSON.stringify( {} ) );

        const outputFile = path.join( options.executionResultDir || '.', 'output.json' );
        let testCommand: string = this.generateTestCommand( options, outputFile );

        const code = await this.runCommand( testCommand );

        return outputFile;
    }

    /**
     * Generates a command that calls CodeceptJS and can be executed in a terminal.
     *
     * @param options Execution options
     * @param outputFile Output file where test results will be written
     * @throws Error
     */
    public generateTestCommand( options: TestScriptExecutionOptions, outputFile: string ): string {
        if ( ! options.sourceCodeDir ) {
            throw new Error( 'Source code directory is missing!' );
        }
        if ( ! options.executionResultDir ) {
            throw new Error( 'Execution result directory is missing!' );
        }
        const commandOptions: object = new CodeceptJSOptionsBuilder()
            .withOutputFile( outputFile )
            .value(); //TODO: Accept CodeceptJS options.
        const optionsStr: string = this.escapeJson( JSON.stringify( commandOptions ) );
        return `codeceptjs run --reporter mocha-multi --override "${optionsStr}" -c ${ options.sourceCodeDir } --colors`;
    }

    private escapeJson( json: string ): string {
        return JSON.stringify( { _: json} ).slice( 6, -2 );
    }

    private async runCommand(
        command: string
    ): Promise< number > {

        let options = {
            // stdio: 'inherit', // <<< not working on windows!
            shell: true
        };

        // Splits the command into pieces to pass to the process;
        //  mapping function simply removes quotes from each piece
        let cmds = command.match( /[^"\s]+|"(?:\\"|[^"])+"/g )
            .map( expr => {
                return expr.charAt( 0 ) === '"' && expr.charAt( expr.length - 1 ) === '"' ? expr.slice( 1, -1 ) : expr;
            } );
        const runCMD = cmds[ 0 ];
        cmds.shift();

        return new Promise< number >( ( resolve, reject ) => {

            const child = childProcess.spawn( runCMD, cmds, options );

            child.stdout.on( 'data', ( chunk ) => {
                console.log( chunk.toString() );
            } );

            child.stderr.on( 'data', ( chunk ) => {
                console.warn( chunk.toString() );
            } );

            child.on( 'exit', ( code ) => {
                resolve( code );
            } );

        } );
    }

}
