export enum UIPropertyTypes {
    ID = 'id',
    TYPE = 'type',
    EDITABLE = 'editable',
    DATA_TYPE = 'datatype',
	REQUIRED = 'required',
    VALUE = 'value',
	FORMAT = 'format',
    MIN_LENGTH = 'minlength',
    MAX_LENGTH = 'maxlength',
    MIN_VALUE = 'minvalue',
    MAX_VALUE = 'maxvalue',
    LOCALE = 'locale',
    LOCALE_FORMAT = 'localeFormat',
}
